'''Constants for the Helty CMV integration.'''

DOMAIN = 'heltycmv'
CMV_NAME_PREFIX = 'VMNM'
NAME_CMD = b'VMNM?'
SENSORS_CMD = b'VMGI?'
CONFIG_GET_CMD = b'VMGH?'
LED_ON_CMD = b'VMWH0100010'
LED_OFF_CMD = b'VMWH0100000'
ATTRIBUTION = 'Helty Flow CMV'
PRESET_BOOST = 'HyperVentilation'
PRESET_NIGHT = 'Night'
PRESET_COOLING = 'FreeCooling'
PRESET_MANUAL = 'Manual'
FAN_LOW = 'Speed 1'
FAN_MEDIUM = 'Speed 2'
FAN_HIGH = 'Speed 3'
FAN_HIGHEST = 'Speed 4'
FAN_AUTO = 'AUTO'
MODE_CMDS = {
    FAN_LOW: b'VMWH0000001',
    FAN_MEDIUM: b'VMWH0000002',
    FAN_HIGH: b'VMWH0000003',
    FAN_HIGHEST: b'VMWH0000004',
    PRESET_BOOST: b'VMWH0000005',
    PRESET_NIGHT: b'VMWH0000006',
    PRESET_COOLING: b'VMWH0000007',
    PRESET_MANUAL: b'VMWH0000001',
}
